### ISSUE TITLE
TypeError: fetch failed with Gitlab

### ISSUE THREAD

**Issue by ebanDev** [baptisteArno/typebot.io#120]
Hi ! I'm using the latest Typebot version with Gitlab as auth. I'm getting this issue when I'm logged in 
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.processResponse (node:internal/deps/undici/undici:6277:34)\n' +
      '    at node:internal/deps/undici/undici:6602:42\n' +
      '    at node:internal/process/task_queues:140:7\n' +
      '    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n' +
      '    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'https://editor.bot.asso.ilearned.eu/api/auth/session',
  message: 'fetch failed'
}
``` 

And it just keeps loading
![image](https://user-images.githubusercontent.com/57091497/185175393-8b9b2466-3910-4b79-b989-1a9bfa73ed64.png)

**Comment by ebanDev** [comment]
Here is my env file : 
```
version: '3.9'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=XXXXX
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://editor.bot.asso.ilearned.eu
      - NEXT_PUBLIC_VIEWER_URL=https://bot.asso.ilearned.eu
      - ENCRYPTION_SECRET=XXXX
      - GITLAB_CLIENT_ID=XXXX
      - GITLAB_CLIENT_SECRET=XXXX
      - GITLAB_BASE_URL=https://gitlab.ilearned.eu
      - GITLAB_NAME=I Learned Gitlab
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://bot.asso.ilearned.eu
      - ENCRYPTION_SECRET=XXXX
volumes:
  db_data:
 ```
