### ISSUE TITLE
S3 configuration problem

### ISSUE THREAD

**Issue by SchBenedikt** [baptisteArno/typebot.io#1258]
I created my Minio bucket as described in the documentation:

```
version: '3.3'

volumes:
  s3-data:

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3-data:/data
  # This service just makes sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
```
and: 
```
S3_ACCESS_KEY=minio
S3_SECRET_KEY=minio123
S3_BUCKET=typebot
S3_ENDPOINT=IP_ADRESS:9000
```
But here I always get this error:

An error occurred while loading the bot.

```
{
  "status": 500,
  "body": {
    "message": "Invalid endPoint : IP_ADRESS:9000",
    "code": "INTERNAL_SERVER_ERROR",
    "data": {
      "code": "INTERNAL_SERVER_ERROR",
      "httpStatus": 500,
      "path": "startChatPreview"
    }
  }
}
```
What could be the reason?
Best regards,
schBenedikt

**Comment by baptisteArno** [comment]
Can you try `localhost` instead of `IP_ADDRESS`?

**Comment by SchBenedikt** [comment]
The same error occurred:
```
{
  "status": 500,
  "body": {
    "message": "Invalid endPoint : localhost:9000",
    "code": "INTERNAL_SERVER_ERROR",
    "data": {
      "code": "INTERNAL_SERVER_ERROR",
      "httpStatus": 500,
      "path": "startChatPreview"
    }
  }
}
```

**Comment by baptisteArno** [comment]
Remove the port from the endpoint:

```
S3_PORT=9000
S3_ENDPOINT=localhost
```

**Comment by SchBenedikt** [comment]
Actually your new config doesn't work for me either:


```
An error occurred while loading the bot.

{
  "status": 500,
  "body": {
    "message": "connect ECONNREFUSED 127.0.0.1:9000",
    "code": "INTERNAL_SERVER_ERROR",
    "data": {
      "code": "INTERNAL_SERVER_ERROR",
      "httpStatus": 500,
      "path": "startChatPreview"
    }
  }
}
```

I also deleted the whole Minio again and reinstalled it, but nothing changed.

**Comment by baptisteArno** [comment]
This isn't the same error. Try with localhost now and make sure your minio config is up and running

**Comment by SchBenedikt** [comment]
Yes I see that. I now simply packed my Minio config into Typebot's .YML file so that Minio doesn't always create a new network, and now I get the same error, but only that port 443 is not reachable. Now I have to look:


```
An error occurred while loading the bot.

{
  "status": 500,
  "body": {
    "message": "connect ECONNREFUSED 127.0.0.1:443",
    "code": "INTERNAL_SERVER_ERROR",
    "data": {
      "code": "INTERNAL_SERVER_ERROR",
      "httpStatus": 500,
      "path": "startChatPreview"
    }
  }
}
```

**Comment by baptisteArno** [comment]
It clearly says that your minio instance is not reachable, this is now out of Typebot scope 🙏

**Comment by SchBenedikt** [comment]
@baptisteArno Thanks for your help! I have now completely revised the config and yml files and now it works.
When everything was running, there was an error with SSL, so I simply set up a domain tunnel with a Cloudflare tunnel. It works now!
Thanks!
Here are my new files; Maybe I'll add instructions for Cloudflare Tunnels in the docs in the next few weeks.
```
version: '3.3'

volumes:
  db-data:
  s3-data:
services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=DB_NAME
      - POSTGRES_PASSWORD=DB_PASSWORT

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
  minio:
    labels:
      virtual.host: 'IP_ADRESS' # change to your domain
      virtual.port: '9000'
      virtual.tls-email: 'admin@example.com' # change to your email
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3-data:/data
  # This service just makes sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
```

and in .ENV I added:

```
S3_ENDPOINT=DOMAIN_WITH_CLOUDFLARE_TUNNEL
S3_ACCESS_KEY=minio
S3_SECRET_KEY=minio123
S3_BUCKET=typebot
```
