### ISSUE TITLE
Unable to Login or Signup After Fresh Self-hosted Installation of TypeBot

### ISSUE THREAD

**Issue by nrashok** [baptisteArno/typebot.io#1273]
After setting up the latest version of TypeBot using self-hosting, admin or users are unable to either login or signup. This issue persists regardless of the authentication method used, whether email, Google, or GitHub.

**Additional Details:**
Upon investigation, the following error messages or behaviors were observed:

1. **Email Signup:** Users encounter an error stating "Email(s) could not be sent."
   ![Email Error Screenshot](https://github.com/baptisteArno/typebot.io/assets/20737358/62bf7710-d789-48ff-a6d7-9f5ea038ac59)

2. **Google or GitHub Signup/Signin:** Users encounter an error message: {"message":"Not found","code":"NOT_FOUND","data":{"code":"NOT_FOUND","httpStatus":404}}
   ![Google/GitHub Signup Error Screenshot](https://github.com/baptisteArno/typebot.io/assets/20737358/2db2bd04-b361-4f0a-b67c-d89a7b733a2c)

**.env File Reference:**
```dotenv
ENCRYPTION_SECRET=5YsZX4IONRUYXKqxxxx
DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
NEXTAUTH_URL=http://tbotdev.mdm1.net:8081
NEXT_PUBLIC_VIEWER_URL=http://tbotdev.mdm1.net:8080
ADMIN_EMAIL=ashokxxxx@gmail.com
# For more configuration options check out: https://docs.typebot.io/self-hosting/configuration
DEFAULT_WORKSPACE_PLAN=UNLIMITED
SMTP_USERNAME=smtpadmin@martake.com
SMTP_PASSWORD=pJxxxx
SMTP_HOST=smtp.martake.com
SMTP_PORT=25
NEXT_PUBLIC_SMTP_FROM=smtpadmin@martake.com
SMTP_SECURE=false
SMTP_AUTH_DISABLED=false
NEXT_PUBLIC_GOOGLE_API_KEY=AIzaSyCr9P8raVNpLH6sxxxx
GOOGLE_CLIENT_ID=620543782984-o6ixxxxx.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-YXHuESJfNVxxxxx
GITHUB_CLIENT_ID=ea41a8xxxxx
GITHUB_CLIENT_SECRET=111fe12377fb420cbc6b416333xxxxx
```

**docker-compose.yaml Reference:**
```yaml
version: '3.3'

volumes:
  db-data:

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
```

Additionally, could anyone suggest an alternative method for logging in as an admin after a fresh installation?
