### ISSUE TITLE
cpu overflow in typebot viewer

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#1354]
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/e89c9675-ad4e-4415-bedd-cdbe4e4a540b)

I have typebot on my machine and at some point the typebot viewer is over 100% and I'm using it in docker swarm in typebot version 2.23.0

My docker swarm configuration:

```
deploy:
      # Define o modo de deploy do container
      mode: replicated
      # Define o numero de replicas do container (sempre 1)
      replicas: 1
      # Define o local de execução do container
      placement:
        constraints:
          - node.role == manager
          # - node.hostname == worker1
      # Define os limites de recursos do container
      resources:
        limits:
          # Define a quantidade de CPU para o Typebot para evitar travamento do Host
          cpus: "3"
          # Define a quantidade de RAM para o Typebot para evitar travamento do Host
          memory: 4024M
```
