### ISSUE TITLE
Streaming not working on Docker deployed app

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1701]

**Comment by baptisteArno** [comment]
Working on docker-compose without proxy

**Comment by baptisteArno** [comment]
https://discord.com/channels/1155799591220953138/1257264634998685706

**Comment by lewiswilliam** [comment]
confirmed its working now

have updated the following in the docker compose file:

```
typebot-builder:
    labels:
      virtual.host: 'typebot.domain.com' # change to your domain name
      virtual.port: '3000'
      virtual.tls-email: 'admin@example.com' # change to your email
      virtual.proxy.directives: |
        flush_interval -1

  typebot-viewer:
    labels:
      virtual.host: 'bot.domain.com' # change to your domain name
      virtual.port: '3000'
      virtual.tls-email: 'admin@example.com' # change to your email
      virtual.proxy.directives: |
        flush_interval -1
```
        
the new setting added is:

```
virtual.proxy.directives: |
        flush_interval -1
```

It maybe a good idea to update it here - https://docs.typebot.io/self-hosting/deploy/docker
