### ISSUE TITLE
Uploading content to a Minio instance doesn't work

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#181]
Hi,
I have installed a Minio instance, but when I try to upload objects to my bucket, a CORS error is returned.
That's weird since Typebot does pass an `Origin` header and my typebot URL is present in the list of allowed origins in the Minio console.
Any clues?

**Comment by Lanhild** [comment]
Double-checked my configuration and that's not where the issue comes from

**Comment by baptisteArno** [comment]
Hey friend,

Have you correctly configured your bucket? Check out this related comment https://github.com/baptisteArno/typebot.io/issues/175#issuecomment-1333637620

**Comment by baptisteArno** [comment]
Any error message in server logs?

**Comment by baptisteArno** [comment]
What's the request that returns à CORS error?

I'll need as much info as possible. Right now I can't guess 🤔

**Comment by Lanhild** [comment]
It's the image upload request to the bucket:

```bash
curl 'https://bucket.domain.tld/typebot' \
  -H 'authority: bucket.domain.tld' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundarygK4B8Y4UN0R2AiBB' \
  -H 'origin: https://bot.domain.tld' \
  -H 'referer: https://bot.domain.tld' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="key"\r\n\r\npublic/results/clbl8s4iv0003pa5ewiy6jz6d/clbfy15yx000b2v6f3mo4u3pf/Screenshot from 2022-12-10 18-47-49.png\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="Content-Type"\r\n\r\nimage/png\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="bucket"\r\n\r\ntypebot\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="X-Amz-Algorithm"\r\n\r\nAWS4-HMAC-SHA256\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="X-Amz-Credential"\r\n\r\n00uorluKDI5dI9XX/20221212/us-east-1/s3/aws4_request\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="X-Amz-Date"\r\n\r\n20221212T210738Z\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="Policy"\r\n\r\neyJleHBpcmF0aW9uIjoiMjAyMi0xMi0xMlQyMToxNzozOFoiLCJjb25kaXRpb25zIjpbWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwxMDQ4NTc2MF0seyJrZXkiOiJwdWJsaWMvcmVzdWx0cy9jbGJsOHM0aXYwMDAzcGE1ZXdpeTZqejZkL2NsYmZ5MTV5eDAwMGIydjZmM21vNHUzcGYvU2NyZWVuc2hvdCBmcm9tIDIwMjItMTItMTAgMTgtNDctNDkucG5nIn0seyJDb250ZW50LVR5cGUiOiJpbWFnZS9wbmcifSx7ImJ1Y2tldCI6InR5cGVib3QifSx7IlgtQW16LUFsZ29yaXRobSI6IkFXUzQtSE1BQy1TSEEyNTYifSx7IlgtQW16LUNyZWRlbnRpYWwiOiIwMHVvcmx1S0RJNWRJOVhYLzIwMjIxMjEyL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QifSx7IlgtQW16LURhdGUiOiIyMDIyMTIxMlQyMTA3MzhaIn1dfQ==\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="X-Amz-Signature"\r\n\r\nba34f3621e7663f74fa28dbb9dbe98a28c3ea83cba59c919d83e8933acba2182\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB\r\nContent-Disposition: form-data; name="file"; filename="Screenshot from 2022-12-10 18-47-49.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundarygK4B8Y4UN0R2AiBB--\r\n' \
  --compressed
```

**Comment by baptisteArno** [comment]
Then the issue isn't related to Typebot unfortunately… It's a misconfiguration on your Minio bucket.

Can you show your bucket access policy rules?

**Comment by Lanhild** [comment]
My bucket configuration is copy-pasted from the post you linked, it's the exact same

**Comment by baptisteArno** [comment]
You're not helping much 😅

Have you configured it via the console? Or via the CLI?

Are you sure you have a "public" folder in your bucket? Can you record a video of your Console so that we can maybe spot what's the issue?

**Comment by Lanhild** [comment]
I'm sorry, but I'm as helpless as you 😆, neither my typebot server nor minio return any logs related to that. I'll investigate again later today and try to give you more info.

**Comment by mihha** [comment]
Let me jump in with the same problem

Here is what is happening in Typebot when I try to upload bot avatar
https://xbackbone.mihha-hosting.com/soJo9/hEloFuGi73.mp4

At the same time, browser error console shows two errors
![image](https://user-images.githubusercontent.com/3791124/209149400-ea93f2b4-e677-4ab2-b860-798098ac82ef.png)

I have created Minio bucket as seen in the following video
https://xbackbone.mihha-hosting.com/soJo9/MoyEMApU54.mp4

Bucket was configured using web console, per suggestion from the issue you suggested 
https://github.com/baptisteArno/typebot.io/issues/175#issuecomment-1333637620

From the console (obviously) I can upload file without any issues
https://xbackbone.mihha-hosting.com/soJo9/bIhoYito29.mp4

I am using Typebot 2.8.10 and Minio 2022-12-12T19:27:27Z, so the latest versions of everything

**Comment by baptisteArno** [comment]
It would be interesting to know what's the error message on the server logs (not the client, which tells nothing)? Do you have that?

**Comment by mihha** [comment]
If you tell me how to collect those server logs, I will gladly provide them

**Comment by baptisteArno** [comment]
So I just deployed this stack locally:

```yml
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://localhost:8080
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:8081
      - ENCRYPTION_SECRET=...
      - ADMIN_EMAIL=...
      - NEXTAUTH_URL_INTERNAL=http://host.docker.internal:8080
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_PORT=9000
      - S3_ENDPOINT=localhost
      - S3_SSL=false
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://localhost:8081
      - ENCRYPTION_SECRET=...
volumes:
  db_data:
  s3_data:
```

I opened http://127.0.0.1:9001 and created a bucket named `typebot`. Then on Typebot, I tried to upload a file, it manages to upload, but then it can't read it (display it) because the bucket is private.

So I added this custom policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::typebot"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::typebot"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "public"
                    ]
                }
            }
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::typebot/public*"
            ]
        }
    ]
}
```

And it worked right away.

@mihha my guess is that your S3 variables are somewhat invalid? Can you tell us what's your config?

PS: To check server logs, if you deployed using docker compose, go to your server terminal and type `docker-compose logs` in the project directory
