### ISSUE TITLE
Error! Could not reach server. Check your connection.  {}

### ISSUE THREAD

**Issue by MehdiRazaNaqvi** [baptisteArno/typebot.io#1880]
**Describe the bug**
When I start the application with` docker-compose up -d`, it starts fine, I can make the flows but when I **Test** the flow, it shows this error 
```
Error! Could not reach server. Check your connection.

{}
```
Although when running through `bunx turbo dev --filter=builder... --filter=viewer...`, it works fine 

Snapshot attached : 

![image](https://github.com/user-attachments/assets/0904e105-31c4-4b09-82d8-514946c76c66)

Here is my docker-compose.yml file : 
```
version: '3.9'

volumes:
  db-data:

services:
  typebot-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 10s
        retries: 5
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      typebot-db:
        condition: service_healthy
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    ports:
      - '8081:3000'
    env_file: .env

```
Also in my .env I have provided these values : 
```
ENCRYPTION_SECRET=
DATABASE_URL=postgresql://postgres:postgres@typebot-db:5432/typebot

NODE_OPTIONS=--no-node-snapshot

NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_VIEWER_URL=http://localhost:3001

ADMIN_EMAIL=
SMTP_USERNAME=
SMTP_PASSWORD-
SMTP_PORT=
SMTP_HOST=
NEXT_PUBLIC_SMTP_FROM=

S3_ACCESS_KEY=
S3_SECRET_KEY=
S3_BUCKET=
S3_ENDPOINT=
```

**To Reproduce**
1. Prepare docker-compose file and run docker-compose up
2. Create the flow / use a template and run '**Test**' on right top.

**Expected behavior**
A clear preview of chatbot which we get using the turbo command mentioned above.
