### ISSUE TITLE
Network Resolution Issue When Migrating Stack Between Portainer Instances

### ISSUE THREAD

**Issue by mordonez** [baptisteArno/typebot.io#2023]
# Network Resolution Issue When Migrating Stack Between Portainer Instances

## Description
When migrating a Typebot stack from one Portainer instance to another, I encountered an issue where container hostname resolution failed. Specifically, `typebot-viewer` was unable to resolve `typebot-db` despite both being in the same network (`typebot_default`).

After inspecting the network using `docker network inspect`, I confirmed that all containers were correctly attached to the default bridge network. 

The issue was ultimately resolved when we set `attachable: true` in the network configuration. Previously, the network was not attachable (`attachable: false`), which seemed to prevent proper hostname resolution between containers.

## Steps to Reproduce
1. Deploy the provided `docker-compose.yml` stack in Portainer.
2. Migrate the stack to another Portainer instance.
3. Observe that `typebot-viewer` cannot resolve `typebot-db`.
4. Check the network settings and confirm `attachable: false`.
5. Modify the network to set `attachable: true` and redeploy.
6. Observe that hostname resolution now works as expected.

## Potential Solution
Would it be advisable to explicitly define the network in `docker-compose.yml` with `attachable: true` to prevent such issues? For example:

```yaml
networks:
  typebot_network:
    driver: bridge
    attachable: true

services:
  typebot-db:
    networks:
      - typebot_network

  typebot-builder:
    networks:
      - typebot_network

  typebot-viewer:
    networks:
      - typebot_network

```

Would adding an explicit network definition with attachable: true help ensure consistent hostname resolution across different Portainer instances?

Expected Behavior

Containers should be able to resolve each other’s hostnames automatically when migrating the stack.

Actual Behavior

typebot-viewer fails to resolve typebot-db hostname after stack migration when attachable: false.

The issue is resolved when attachable: true is set.

Looking forward to your thoughts on this. Thanks!
