### ISSUE TITLE
Authentication failed against database server at `typebot-db`

### ISSUE THREAD

**Issue by satoshinotdead** [baptisteArno/typebot.io#338]
I'm trying to install typebot on docker behind Nginx. We have 5 apps running but I just can't make typebot works.

```
Waiting 5s for db to be ready...
Prisma schema loaded from packages/db/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"

Error: P1000: Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.

Please make sure to provide valid database credentials for the database server at `typebot-db`.
info  - Loaded env from /app/apps/builder/.env.production
Listening on port 3000 url: http://79327f00d95e:3000
```

Domains are working but I can't write on the database. Tried so many options on docker-compose.yml like localhost, local IP of container, 127.0.0.1, host.docker.internal and more.

What's the correct DATABASE_URL and  or database configuration for Docker? Can you please figure how to configure it on production?

Thanks to [baptiste](https://github.com/baptisteArno) and the community around for Typebot :)

**Comment by baptisteArno** [comment]
This is the simplest docker-compose you can have:

```yml
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=<your-builder-url>
      - NEXT_PUBLIC_VIEWER_URL=<your-viewer-url>
      - ENCRYPTION_SECRET=<your-encryption-secret>
      - ADMIN_EMAIL=<your-admin-email>
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=<your-viewer-url>
      - ENCRYPTION_SECRET=<your-encryption-secret>
volumes:
  db_data:
```

This should work right off the bat. Do you have any other info about how your server deploys application? Can you show maybe a bit of your docker-compose file?

**Comment by satoshinotdead** [comment]
Of course, that's my config:

```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgres://typebot:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=BUILDER
      - NEXT_PUBLIC_VIEWER_URL=VIEWER
      - ENCRYPTION_SECRET=
      - ADMIN_EMAIL=MAIL
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgres://typebot:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://VIEWR
      - ENCRYPTION_SECRET=
      - NEXT_PUBLIC_VIEWER_INTERNAL_URL=http://127.0.0.1:8081
volumes:
  db_data:
```

And that's the error I get:

```
Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"

Error: P1000: Authentication failed against database server at `typebot-db`, the provided database credentials for `typebot` are not valid.
```
