### ISSUE TITLE
Getting an error while trying to load or preview a form

### ISSUE THREAD

**Issue by Dannesch** [baptisteArno/typebot.io#355]
Erlier today i was trying to setup an instance of typebot behind a traefik proxy. And i get the following error when i try to preview the form: Error! Couldn't initiate the chat. And when i try to use the published app it gives me this error: The bot you're looking for doesn't exist

![image](https://user-images.githubusercontent.com/35847188/222764321-1e7d5317-fbbe-49b2-8a3b-dae391eca88b.png)
![image](https://user-images.githubusercontent.com/35847188/222764409-e8d50773-ddd4-41ef-a827-c9f6b9b245a2.png)

**Please note that i replaced the sencitive information**

Here's the compose file:
```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    networks:
      - proxy

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    networks:
      - proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=typebot.my-domain.com
      - NEXT_PUBLIC_VIEWER_URL=bot.my-domain.com
      - ENCRYPTION_SECRET=****
      - ADMIN_EMAIL=admin-email@domain.com
      - GITHUB_CLIENT_ID=***client-id****
      - GITHUB_CLIENT_SECRET=******

      - SMTP_USERNAME=my-email@domain.com
      - SMTP_PASSWORD=****
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - NEXT_PUBLIC_SMTP_FROM=my-email@domain.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typebot-builder.entrypoints=http"
      - "traefik.http.routers.typebot-builder.rule=Host(`typebot.my-domain.com`)"
      - "traefik.http.middlewares.typebot-builder-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.typebot-builder.middlewares=typebot-builder-https-redirect"
      - "traefik.http.routers.typebot-builder-secure.entrypoints=https"
      - "traefik.http.routers.typebot-builder-secure.rule=Host(`typebot.my-domain.com`)"
      - "traefik.http.routers.typebot-builder-secure.tls=true"
      - "traefik.http.routers.typebot-builder-secure.service=typebot-builder"
      - "traefik.http.services.typebot-builder.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    networks:
      - proxy
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=bot.my-domain.com
      - ENCRYPTION_SECRET=****
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.typebot-viewer.entrypoints=http"
      - "traefik.http.routers.typebot-viewer.rule=Host(`bot.my-domain.com`)"
      - "traefik.http.middlewares.typebot-viewer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.typebot-viewer.middlewares=typebot-viewer-https-redirect"
      - "traefik.http.routers.typebot-viewer-secure.entrypoints=https"
      - "traefik.http.routers.typebot-viewer-secure.rule=Host(`bot.my-domain.com`)"
      - "traefik.http.routers.typebot-viewer-secure.tls=true"
      - "traefik.http.routers.typebot-viewer-secure.service=typebot-viewer"
      - "traefik.http.services.typebot-viewer.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

volumes:
  db_data:

networks:
  proxy:
    external: true
```

Here are the logs: [logs.txt](https://github.com/baptisteArno/typebot.io/files/10883912/logs.txt) (it's in file form because it was too long)
