### ISSUE TITLE
Share tab on self-hosted instance has typebot.io URLs

### ISSUE THREAD

**Issue by CiRIP** [baptisteArno/typebot.io#435]
Going to the Share tab on a self-hosted instance shows you a typebot.io link, and any embed option is configured for the managed service (except for WordPress which shows `apiHost="undefined"`).

**Comment by baptisteArno** [comment]
Have you set up your `NEXT_PUBLIC_VIEWER_URL` environment variable correctly on your builder container?

**Comment by CiRIP** [comment]
Yes, it seems so. Just rebooted it now, the flag shows up in the startup logs for the builder, but it's still typebot.io in the share tab.

**Comment by baptisteArno** [comment]
Can you show your docker-compose config without sensitive information?

**Comment by CiRIP** [comment]
Sure, here it is:

```yaml
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=<redacted>
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:<redacted>@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://builder.<redacted>.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXT_PUBLIC_VIEWER_URL=https://chat.<redacted>.com
      - ENCRYPTION_SECRET=<redacted>
      - ADMIN_EMAIL=<redacted>
      - SMTP_HOST=smtp.<redacted>.com
      - SMTP_PORT=25
      - NEXT_PUBLIC_SMTP_FROM="Typebot Notifications" <noreply@<redacted>.com>
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:<redacted>@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://chat.<redacted>.com
      - NEXTAUTH_URL=https://builder.<redacted>.com
      - ENCRYPTION_SECRET=<redacted>
      - SMTP_HOST=smtp.<redacted>.com
      - SMTP_PORT=25
      - SMTP_FROM="Typebot Notifications" <noreply@<redacted>.com>
volumes:
  db_data:
```
