### ISSUE TITLE
Error! Couldn't initiate the chat.

### ISSUE THREAD

**Issue by adelorenzo-portainer** [baptisteArno/typebot.io#460]
Hello,

I am getting the following error: `Error! Couldn't initiate the chat.`
Brand new self-hosted docker deployment. Please, any idea why?

<img width="811" alt="Screenshot 2023-04-13 at 9 54 20 PM" src="https://user-images.githubusercontent.com/81579885/231937678-2e48442d-28ce-4f5e-8efb-08f9b0e7209e.png">

my compose file:

```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8077:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.example.com
      - NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
      - ENCRYPTION_SECRET=<my secret>
      - ADMIN_EMAIL=<my email>
      - SMTP_USERNAME=<my username>
      - SMTP_PASSWORD=<my password>
      - SMTP_HOST=<my email server>
      - SMTP_PORT=465
      - NEXT_PUBLIC_SMTP_FROM='my typebot'
      - SMTP_SECURE=true
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8078:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://bot.k2c.live
      - ENCRYPTION_SECRET=<my secret>
volumes:
  db_data:
```

I removed/altered the sensitive info. DNS records are ok and tested. Thank you very much.
