### ISSUE TITLE
Media storage - local storage

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#56]
I am plying with Typebot now that I was finally able to install it properly

I saw that in order to upload your own images, you have to configure some S3 like storage

Would it be possible to use server local storage for media uploads, instead of S3 compatible storage?

**Comment by baptisteArno** [comment]
> Would it be possible to use server local storage for media uploads, instead of S3 compatible storage?

Unfortunately, no.

Though, implementing an S3 service is pretty straightforward with docker-compose. Here is the config for localhost:

```yaml
version: '3.6'
services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data
  # This service just makes sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc policy set public minio/typebot/public;
      exit 0;
      "
volumes:
  s3_data:
```

And the environment variables would be:

```
S3_ACCESS_KEY=minio
S3_SECRET_KEY=minio123
S3_BUCKET=typebot
S3_PORT=9000
S3_ENDPOINT=localhost
S3_SSL=false
```

Does that make sense?
