### ISSUE TITLE
I can't upload file

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#574]
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/47291747-d463-45fc-b4da-3afa4fd45f57)
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/0c9ccb56-8c83-44c0-a374-7a2bd5d67172)
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/ffbe3eeb-7de8-475d-8071-cb7ee87ed83a)

```
  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    networks:
      - root_default
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data

    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.xxxxxxxx.com.br`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.entrypoints=web,websecure
      - traefik.http.routers.minio.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.minio.headers.SSLRedirect=true
      - traefik.http.middlewares.minio.headers.STSSeconds=315360000
      - traefik.http.middlewares.minio.headers.browserXSSFilter=true
      - traefik.http.middlewares.minio.headers.contentTypeNosniff=true
      - traefik.http.middlewares.minio.headers.forceSTSHeader=true
      - traefik.http.middlewares.minio.headers.SSLHost=360leads.com.br
      - traefik.http.middlewares.minio.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.minio.headers.STSPreload=true
      - traefik.http.routers.minio.middlewares=minio@docker
```

to use traefik
