### ISSUE TITLE
Viewer - bot.example.com is getting a 404 and cannot send emails to sign up using SMTP

### ISSUE THREAD

**Issue by smit-io** [baptisteArno/typebot.io#576]
Hi,

For the selfhosted version I am getting a 404 on my viewer URL - bot.example.com and getting "Unauthorized, sign ups are disabled" error on typebot.example.com.

I have a google workspace for my domain and trying to use the smtp relay for gmail to get things working. Any help is appreciated.

This is my docker compose
```
version: '3.3'

services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - /home/user/typebot/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '4000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration/builder for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebot.example.com
      - NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
      - ENCRYPTION_SECRET=secret
      - ADMIN_EMAIL=admin@example.com
      - SMTP_HOST=smtp-relay.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=admin@example.com
      - SMTP_PASSWORD=password
      - NEXT_PUBLIC_SMTP_FROM=admin@example.com
      - SMTP_SECURE=true
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '4001:3000'
    # See https://docs.typebot.io/self-hosting/configuration/viewer for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
      - ENCRYPTION_SECRET=secret 
      - NEXTAUTH_URL=https://typebot.example.com
   ```

Here are the logs:

from builder service
```
env.sh loaded
Matched inline env:
NEXT_PUBLIC_SMTP_FROM=admin@example.com
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
Reading ./apps/builder/.env.production...
NEXT_PUBLIC_VIEWER_URL=
NEXT_PUBLIC_SMTP_FROM=
NEXT_PUBLIC_GOOGLE_API_KEY=
NEXT_PUBLIC_GIPHY_API_KEY=
NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
NEXT_PUBLIC_SENTRY_DSN=
NEXT_PUBLIC_VIEWER_INTERNAL_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
NEXT_PUBLIC_UNSPLASH_APP_NAME=
NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
NEXT_PUBLIC_SMTP_FROM=admin@example.com
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Checking if required environment variables are set and valid...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
✔ Generated Prisma Client (4.14.1 | library) to ./node_modules/.pnpm/@prisma+client@4.14.1_prisma@4.14.1/node_modules/@prisma/client in 213ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Waiting 5s for db to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
52 migrations found in prisma/migrations
No pending migrations to apply.
┌─────────────────────────────────────────────────────────┐
│  Update available 4.14.1 -> 4.16.1                      │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
- info Loaded env from /app/apps/builder/.env.production
Listening on port 3000 url: http://9190040a5845:3000
- info Loaded env from /app/apps/builder/.env.production
(node:233) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
  error: {
    message: 'Email(s) could not be sent',
    stack: 'Error: Email(s) could not be sent\n' +
      '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/5960.js:330:15)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async email (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
      '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
      '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.4.3_nodemailer@6.9.2_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async handler (/app/apps/builder/.next/server/chunks/5960.js:527:12)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'Email(s) could not be sent'
}

```

From viewer service

```
env.sh loaded
Matched inline env:
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
Reading ./apps/viewer/.env.production...
NEXT_PUBLIC_VIEWER_URL=
NEXT_PUBLIC_E2E_TEST=
NEXT_PUBLIC_VIEWER_URL=https://bot.example.com
Got index from inline env: 0, replacing NEXT_PUBLIC_VIEWER_URL
env.sh done
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
✔ Generated Prisma Client (4.14.1 | library) to ./node_modules/.pnpm/@prisma+client@4.14.1_prisma@4.14.1/node_modules/@prisma/client in 223ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
- info Loaded env from /app/apps/viewer/.env.production
Listening on port 3000 url: http://92fc660be5aa:3000
- info Loaded env from /app/apps/viewer/.env.production

```

from db service

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-06-25 04:39:49.601 UTC [1] LOG:  starting PostgreSQL 13.11 (Debian 13.11-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-06-25 04:39:49.607 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-06-25 04:39:49.607 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-06-25 04:39:49.609 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-06-25 04:39:49.611 UTC [27] LOG:  database system was shut down at 2023-06-25 04:36:32 UTC
2023-06-25 04:39:49.616 UTC [1] LOG:  database system is ready to accept connections
2023-06-25 04:39:55.982 UTC [34] LOG:  could not receive data from client: Connection reset by peer
2023-06-25 04:43:40.050 UTC [44] LOG:  could not receive data from client: Connection reset by peer


```
