### ISSUE TITLE
Can't sign in with the latest version 2.2.0

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#78]
Guys, if you remember, I had huge problems making version 2.1.0 to work on my environment

Now that you are providing your docker images, I tried to use new method, and again I have a problem with the sign in

This is my docker-compose.yml file for version 2.2.0

```
version: '3.9'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '38080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://typebotapp.mihha-hosting.com
      - NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
      - ENCRYPTION_SECRET=<MY_SECRET_KEY_IS_HERE>
      - ADMIN_EMAIL=<MY_EMAIL_IS_HERE>
      - SMTP_AUTH_DISABLED=false
      - SMTP_USERNAME=<MY_CORRECT_SMTP_USERNAME_IS_HERE>
      - SMTP_PASSWORD=<MY_CORRECT_SMTP_PASSWORD_IS_HERE>
      - SMTP_HOST=<MY_CORRECT_SMTP_HOST_IS_HERE>
      - SMTP_PORT=465
      - SMTP_FROM=<MY_CORRECT_SMTP_FROM_IS_HERE>
      - NEXT_PUBLIC_GIPHY_API_KEY=<MY_CORRECT_GIPHY_API_KEY_IS_HERE>
      - S3_ACCESS_KEY=<MY_CORRECT_S3_ACCESS_KEY_IS_HERE>
      - S3_SECRET_KEY=<MY_CORRECT_S3_SECRET_KEY_IS_HERE>
      - S3_BUCKET=typebot
      - S3_ENDPOINT=<MY_CORRECT_S3_ENDPOINT_IS_HERE>
      - S3_SSL=true
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '38081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
      - ENCRYPTION_SECRET=<MY_SECRET_KEY_IS_HERE>
      - SMTP_USERNAME=<MY_CORRECT_SMTP_USERNAME_IS_HERE>
      - SMTP_PASSWORD=<MY_CORRECT_SMTP_PASSWORD_IS_HERE>
      - SMTP_HOST=<MY_CORRECT_SMTP_HOST_IS_HERE>
      - SMTP_PORT=465
      - SMTP_FROM=<MY_CORRECT_SMTP_FROM_IS_HERE>
volumes:
  db_data:
```

I am staring at this and can't find an error

Even though I have email authentication enabled, I am still receiving this when I visit the Builder interface
![image](https://user-images.githubusercontent.com/3791124/172150115-4fcb359e-d1f8-4741-90d4-de05009d3bdf.png)
