### ISSUE TITLE
Add instructions on how to properly configure NGINX forwarded host

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#840]
### Discussed in https://github.com/baptisteArno/typebot.io/discussions/826

<div type='discussions-op-text'>

<sup>Originally posted by **Robert-J-Barros** September 19, 2023</sup>
### 
hey guys

When accessing the viewer url of my published chat I receive the error "404
The bot you're looking for doesn't exist" 
![image](https://github.com/baptisteArno/typebot.io/assets/105607298/68283b3f-fda3-43bb-b636-5e905e45b3a6) 
![image](https://github.com/baptisteArno/typebot.io/assets/105607298/02ad2c2c-f546-47c3-b4b8-07a203e63bfc)

I viewed the container logs and apparently everything is normal.
![image](https://github.com/baptisteArno/typebot.io/assets/105607298/fcf304c6-404c-410c-bc63-ff8013e077ce)

currently docker-compose.yml is defined as follows:
```
version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - ${PWD}/.typebot/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
```
My set environment variables are as follows:

```
ENCRYPTION_SECRET=do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta
DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
NEXTAUTH_URL=https://typebot.fairness.com.br
NEXT_PUBLIC_VIEWER_URL=https://bot.fairness.com.br
ADMIN_EMAIL=robert.junior.goncalves@gmail.com
SMTP_HOST=smtp.email.sa-saopaulo-1.oci.oraclecloud.com 
SMTP_PORT=587 
SMTP_USERNAME=ocid1.user.oc1..aaaaaaaazicvws42iswxwncmfevpd2nit3gnzvby4l2mzs5zshh3ikk6khmq@ocid1.tenancy.oc1..aaaaaaaakpvlqegag66ttckxyjzhhbllfqyiuxakpzuw7nyilf2x7afqkbwa.o4.com 
SMTP_PASSWORD=uppO;spEi!QUz+S}g-0< 
SMTP_SECURE=false
```

When inspecting the page I notice that the variables are being defined:

![image](https://github.com/baptisteArno/typebot.io/assets/105607298/6ba962a1-386f-42cd-b94f-b48ad90c721e)

</div>
