### ISSUE TITLE
Issue with local email authentication on self hosted instance of typebot

### ISSUE THREAD

**Issue by Streethawk27** [baptisteArno/typebot.io#967]
Hello.

I set up a local typebot instance on docker. 
Containers are starting and are accessible.
I am using traefik as reverse proxy. 

After typing my mail-address on the signup screen, nothing happens, no error message, no timeout, nothing.

![image](https://github.com/baptisteArno/typebot.io/assets/88531074/2b3009ed-79e7-48dd-9f91-e8c7fcce0a5a)

In the typebot-builder container there is no logmessage as well.
In the Javascript console no messages as well.

The request to https://typebot.subdomain.domain.de/api/auth/signin/email? never comes back.

Post-Data from the request:
```
email: a@b.com
redirect: false
csrfToken: 8c4e8fd5d6a8f51014364a278306e7b302c2a228ebecc0e3e48a7ddedad1851c
callbackUrl: https://typebot.subdomain.domain.de/de/signin
json: true
```

My local mailserver is accessible without authentication - could that be a problem?

docker-compose.yml

```
version: '3.3'

volumes:
  db-data:

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
    networks:
      - typebot

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.typebot-redirect-https.redirectscheme.scheme=https
      - traefik.http.routers.typebot.middlewares=typebot-redirect-https
      - traefik.http.routers.typebot.rule=Host(`typebot.subdomain.domain.de`)
      - traefik.http.routers.typebot.entrypoints=http
      - traefik.http.routers.typebot-https.rule=Host(`typebot.subdomain.domain.de`)
      - traefik.http.routers.typebot-https.tls=true
      - traefik.http.routers.typebot-https.entrypoints=https
      - traefik.docker.network=traefik
      - traefik.http.services.typebot.loadbalancer.server.port=3000
    networks:
      - traefik
      - typebot

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.bot-redirect-https.redirectscheme.scheme=https
      - traefik.http.routers.bot.middlewares=bot-redirect-https
      - traefik.http.routers.bot.rule=Host(`bot.subdomain.domain.de`)
      - traefik.http.routers.bot.entrypoints=http
      - traefik.http.routers.bot-https.rule=Host(`bot.subdomain.domain.de`)
      - traefik.http.routers.bot-https.tls=true
      - traefik.http.routers.bot-https.entrypoints=https
      - traefik.docker.network=traefik
      - traefik.http.services.bot.loadbalancer.server.port=3000
    networks:
      - traefik
      - typebot


networks:
  traefik:
    external: true
  typebot:
    external: true
```

.env
```
# Make sure to change this to your own random string of 32 characters (https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
ENCRYPTION_SECRET=YY2rXphT6zxtwa9+o5X822ojrdSr2CSz

DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot

NEXTAUTH_URL=https://typebot.subdomain.domain.de
NEXT_PUBLIC_VIEWER_URL=https://bot.subdomain.domain.de

ADMIN_EMAIL=a@example.com
# For more configuration options check out: https://docs.typebot.io/self-hosting/configurationi

NEXTAUTH_URL_INTERNAL=http://typebot-builder:3000

SMTP_HOST=192.168.156.150
SMTP_PORT=25
SMTP_SECURE=false
SMTP_AUTH_DISABLED=false

NEXT_PUBLIC_SMTP_FROM=typebot@subdomain.domain.de

DEBUG=true
DISABLE_SIGNUP=false
DEFAULT_WORKSPACE_PLAN=UNLIMITED
```

Log messages in builder-container:
```
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/builder/public/__ENV.js'.
Waiting for 15s for database to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"

57 migrations found in prisma/migrations


No pending migrations to apply.
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 651ms
```

Docker Image is:
baptistearno/typebot-builder     latest      699d631d0f8e

Thank you.
Bye
Christoph
